spring:
  datasource:
    url: jdbc:mysql://localhost/bookstore?createDatabaseIfNotExist=true
    username: root
    driver-class-name: com.mysql.jdbc.Driver

---
spring:
  profiles: production
  datasource:
    url: jdbc:postgresql//${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
